### ISSUE TITLE
Tasks todo

### ISSUE THREAD

**Issue by h0x0er** [h0x0er/-kbanalysis-#6]
- [ ] Show if action is `Docker based ` or `Node based`
- [ ] Add queries for `Octokit` or similar words.
- [ ] Search for `token` in `Readme.md`
- [ ] If `action`  doesn't use token, then add a `yaml code` for that action, indicating `doesn't use token`
